workflows:
  flutter_workflow:
    name: Build Flutter App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Installer les dépendances Flutter
        script: flutter pub get

    # Build Android APK
   
    
      - name: Build iOS IPA
        script: flutter build ipa --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "bamoussa220@gmail.com"
