// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjfCcC-r0ZOy9Ey0qIfauwSwB_86RhsxY',
    appId: '1:864261936480:web:086f05dcb087181a46ba05',
    messagingSenderId: '864261936480',
    projectId: 'bakhbade-4daa5',
    authDomain: 'bakhbade-4daa5.firebaseapp.com',
    storageBucket: 'bakhbade-4daa5.firebasestorage.app',
    measurementId: 'G-B8NCFVL0R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdEklA6hdDcRVUDHNrWAbOxfk4EU_778Y',
    appId: '1:864261936480:android:c80b904b29e5ce8246ba05',
    messagingSenderId: '864261936480',
    projectId: 'bakhbade-4daa5',
    storageBucket: 'bakhbade-4daa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7xznl1B_9AA12JmcY-oMXJPgpveA1IQw',
    appId: '1:864261936480:ios:4c4e64765880457646ba05',
    messagingSenderId: '864261936480',
    projectId: 'bakhbade-4daa5',
    storageBucket: 'bakhbade-4daa5.firebasestorage.app',
    iosBundleId: 'com.example.bakhbade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7xznl1B_9AA12JmcY-oMXJPgpveA1IQw',
    appId: '1:864261936480:ios:4c4e64765880457646ba05',
    messagingSenderId: '864261936480',
    projectId: 'bakhbade-4daa5',
    storageBucket: 'bakhbade-4daa5.firebasestorage.app',
    iosBundleId: 'com.example.bakhbade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjfCcC-r0ZOy9Ey0qIfauwSwB_86RhsxY',
    appId: '1:864261936480:web:086f05dcb087181a46ba05',
    messagingSenderId: '864261936480',
    projectId: 'bakhbade-4daa5',
    authDomain: 'bakhbade-4daa5.firebaseapp.com',
    storageBucket: 'bakhbade-4daa5.firebasestorage.app',
    measurementId: 'G-B8NCFVL0R5',
  );

}